<logs><log LogGUID="55fcad05-17aa-483f-8897-0d472e685da1" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:32:34 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>0fd3932b-cd5d-4c4b-b0ba-b24f1f0cd889</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>c32aJRGtqoO2ZgnR1MLaxQ==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetHostSettings()
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The network path was not found</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="47fbe399-1d29-4dbc-8f7e-a2d5d5afcc21" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:32:34 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>24c7d635-14a4-4bd6-9092-5609b1ca09f1</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>iSwMTIbb9wGrgDAJAtGZbg==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetPortalAliases()
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The network path was not found</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="cc521933-e7ac-4ab2-924d-a596c4707626" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:32:34 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAlias(String alias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at Do</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAlias(String alias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Enti</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="1e067712-ef10-4596-81c1-b1dba8c00ff3" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:32:36 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>No shutdown reason provided.</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="417a9435-e944-4130-8765-f6464f9509e1" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:33:07 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>6f66cf6a-5878-43e8-9b39-8730399447aa</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>S855XfP3Cjz7zs66uUtZEg==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetHostSettings()
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The network path was not found</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="c62c1b04-4837-48e4-9fce-0a7400e1bc5f" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:33:07 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>9455074b-f3db-4e4a-b46d-74190fa728d6</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>nu/51A+1/DnjQiibBLivKA==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetPortalAliases()
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The network path was not found</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="4e2573b2-be51-43b7-a0f4-791be83d7eca" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:33:07 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAlias(String alias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at Do</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAlias(String alias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Enti</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="d0767c06-38d7-41f6-b31b-f7c170bc7628" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:33:08 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the application level configuration.</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="f06fda8a-cb60-4672-aff7-d36baaa82d17" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:33:26 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>90448bba-ca02-41e3-a8b1-ac2942f0cad2</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>/1GTPb6EHUuf02PTLVbJaw==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The requested name is valid, but no data of the requested type was found.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetHostSettings()
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The requested name is valid, but no data of the requested type was found</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="6d344c12-f99a-421e-94cd-9d3a04f06f44" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:33:26 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>43dba464-489d-4b61-860d-6ce97c313508</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>wdApPGI2aD+mVZGtyQRHLw==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The requested name is valid, but no data of the requested type was found.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetPortalAliases()
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The requested name is valid, but no data of the requested type was found</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="1660bd31-5360-4e9b-b76e-b39f84fe684e" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:33:26 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAlias(String alias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at Do</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAlias(String alias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Enti</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="05012a9f-7fbd-4567-950b-1f91412f41b4" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="4/6/2015 5:33:55 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>2afe4447-26fc-4309-be46-3441eb8face3</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>rox0w3FXjN8NeWik3rvQlQ==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The requested name is valid, but no data of the requested type was found.)</Message><StackTrace>   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetPortalAliases()
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The requested name is valid, but no data of the requested type was found</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="8e515656-3c86-4b13-81a5-7ac905bb911e" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="0" LogPortalName="NEXSO" LogCreateDate="5/21/2015 1:48:39 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Sinapsis-02" LogConfigID="4"><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/Default.aspx</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>11dab80a-c605-4577-b37d-650bb4477b35</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>K/XQ8zEydlio3bynUt38mA==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Message><StackTrace>   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetRedirections(Int32 portalId)
   at DotNetNuke.Services.Mobile.RedirectionController.GetRedirectionsByPortalCallBack(CacheItemArgs cacheItemArgs)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage /><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="221470b3-87b2-4b67-afe1-434e7e62ddf5" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="0" LogPortalName="NEXSO" LogCreateDate="5/21/2015 1:49:26 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Sinapsis-02" LogConfigID="4"><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/Default.aspx</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>b5bcd672-a78d-4d42-9e39-3697663e72a3</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>pZrh+PZWQ9X4kCZG1w2WDA==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Message><StackTrace>   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeout, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetRedirections(Int32 portalId)
   at DotNetNuke.Services.Mobile.RedirectionController.GetRedirectionsByPortalCallBack(CacheItemArgs cacheItemArgs)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage /><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="a5751b5c-5ea8-4d21-9d91-a3991187db20" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="12/3/2015 4:30:02 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="JAIROA" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>No shutdown reason provided.</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="8242dd8f-9210-4b70-941f-5fb50e3e6735" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="12/7/2015 9:11:41 AM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the application level configuration.</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="8968a111-3571-48e2-b356-507b94cba754" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>8a000c4c-751c-4b0b-8095-21255c925a11</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>pWxAThGiFACHrYZIEO5Pzg==</ExceptionHash><Message>Subproceso anulado.</Message><StackTrace>   en DotNetNuke.Collections.Internal.ReaderWriterLockStrategy.GetReadLock(TimeSpan timeout)
   en DotNetNuke.Collections.Internal.SharedDictionary`2.GetReadLock(TimeSpan timeOut)
   en DotNetNuke.Collections.Internal.SharedDictionary`2.GetReadLock()
   en DotNetNuke.ComponentModel.SimpleContainer.GetDefaultComponentBuilder(ComponentType componentType)
   en DotNetNuke.ComponentModel.SimpleContainer.GetComponent(Type contractType)
   en DotNetNuke.ComponentModel.AbstractContainer.GetComponent[TContract]()
   en DotNetNuke.ComponentModel.ComponentFactory.GetComponent[TContract]()
   en DotNetNuke.Services.Cache.CachingProvider.Instance()
   en DotNetNuke.Common.Utilities.DataCache.GetCache(String CacheKey)
   en DotNetNuke.Common.Utilities.CBO.GetObjectMapping(Type objType)
   en DotNetNuke.Common.Utilities.CBO.HydrateObject(Object hydratedObject, IDataReader dr)
   en DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
   en DotNetNuke.Common.Utilities.CBO.CreateObjectFromReader(Type objType, IDataReader dr, Boolean closeReader)
   en DotNetNuke.Common.Utilities.CBO.FillListFromReader(Type objType, IDataReader dr, IList objList, Boolean closeReader)
   en DotNetNuke.Common.Utilities.CBO.FillCollection(IDataReader dr, Type objType)
   en DotNetNuke.Modules.Html.WorkflowStateController.GetWorkflows(Int32 PortalID)
   en DotNetNuke.Modules.Html.HtmlTextController.GetWorkflow(Int32 ModuleId, Int32 TabId, Int32 PortalId)
   en DotNetNuke.Modules.Html.HtmlTextController.GetModifiedSearchDocuments(ModuleInfo modInfo, DateTime beginDateUtc)
   en DotNetNuke.Services.Search.ModuleIndexer.GetSearchDocuments(Int32 portalId, DateTime startDateLocal)</StackTrace><InnerMessage /><InnerStackTrace /><Source>DotNetNuke</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="e63ffaf8-2d30-4c4c-90b5-7c92e08f5527" LogFileID="" LogTypeKey="SCHEDULER_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>b67c6073-f207-4713-883e-a8241b65d582</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>7hnMwu5+0cMPqtF44AYFfw==</ExceptionHash><Message>Subproceso anulado.</Message><StackTrace>   en DotNetNuke.Services.Search.ModuleIndexer.GetSearchDocuments(Int32 portalId, DateTime startDateLocal)
   en DotNetNuke.Services.Search.SearchEngine.GetSearchDocuments(IndexingProvider indexer, DateTime startDateLocal)
   en DotNetNuke.Services.Search.SearchEngine.IndexContent(DateTime startDate)
   en DotNetNuke.Services.Search.SearchEngineScheduler.DoWork()</StackTrace><InnerMessage /><InnerStackTrace /><Source>DotNetNuke</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="f1dfe02a-bdde-4dd7-bcdf-a5856577874d" LogFileID="" LogTypeKey="SCHEDULER_EVENT_FAILURE" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>THREAD ID</PropertyName><PropertyValue>49</PropertyValue></LogProperty><LogProperty><PropertyName>TYPE</PropertyName><PropertyValue>DotNetNuke.Services.Search.SearchEngineScheduler, DOTNETNUKE</PropertyValue></LogProperty><LogProperty><PropertyName>EXCEPTION</PropertyName><PropertyValue>Subproceso anulado.</PropertyValue></LogProperty><LogProperty><PropertyName>RESCHEDULED FOR</PropertyName><PropertyValue>09/12/15 13:59:31</PropertyValue></LogProperty><LogProperty><PropertyName>SOURCE</PropertyName><PropertyValue>STARTED_FROM_TIMER</PropertyValue></LogProperty><LogProperty><PropertyName>ACTIVE THREADS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>FREE THREADS</PropertyName><PropertyValue>1</PropertyValue></LogProperty><LogProperty><PropertyName>READER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>WRITER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN PROGRESS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN QUEUE</PropertyName><PropertyValue>5</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="86c71ea4-e742-4319-a28b-5dc79a5abef4" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>395ace99-d27c-4004-a2f7-1703f0ae2495</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>nIMU99CF2ds+AmL2FZ0SbQ==</ExceptionHash><Message>Subproceso anulado.</Message><StackTrace>   en DotNetNuke.Services.Search.ModuleIndexer.GetSearchDocuments(Int32 portalId, DateTime startDateLocal)
   en DotNetNuke.Services.Search.SearchEngine.GetSearchDocuments(IndexingProvider indexer, DateTime startDateLocal)
   en DotNetNuke.Services.Search.SearchEngine.IndexContent(DateTime startDate)
   en DotNetNuke.Services.Search.SearchEngineScheduler.DoWork()</StackTrace><InnerMessage /><InnerStackTrace /><Source>DotNetNuke</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="d32ecd92-8b3d-473b-bf5c-14e346b5e07d" LogFileID="" LogTypeKey="SCHEDULER_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>904524c2-d385-42ce-a69e-094fa3782854</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>V0lnFi1xWIGfa89YyFZ7DA==</ExceptionHash><Message>Subproceso anulado.</Message><StackTrace>   en DotNetNuke.Services.Search.SearchEngineScheduler.DoWork()
<<<<<<< HEAD
   en DotNetNuke.Services.Scheduling.ProcessGroup.Run(ScheduleHistoryItem objScheduleHistoryItem)</StackTrace><InnerMessage /><InnerStackTrace /><Source>DotNetNuke</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="f03cca3c-e850-4b87-b08a-f25e7037bccc" LogFileID="" LogTypeKey="SCHEDULER_EVENT_FAILURE" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>THREAD ID</PropertyName><PropertyValue>49</PropertyValue></LogProperty><LogProperty><PropertyName>TYPE</PropertyName><PropertyValue>DotNetNuke.Services.Search.SearchEngineScheduler, DOTNETNUKE</PropertyValue></LogProperty><LogProperty><PropertyName>EXCEPTION</PropertyName><PropertyValue>Subproceso anulado.</PropertyValue></LogProperty><LogProperty><PropertyName>RESCHEDULED FOR</PropertyName><PropertyValue>01/01/01 00:00:30</PropertyValue></LogProperty><LogProperty><PropertyName>SOURCE</PropertyName><PropertyValue>STARTED_FROM_TIMER</PropertyValue></LogProperty><LogProperty><PropertyName>ACTIVE THREADS</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>FREE THREADS</PropertyName><PropertyValue>2</PropertyValue></LogProperty><LogProperty><PropertyName>READER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>WRITER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN PROGRESS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN QUEUE</PropertyName><PropertyValue>5</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="59dd5faa-7bac-4513-9dc1-09ef220e4de4" LogFileID="" LogTypeKey="SCHEDULER_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>be8147e6-ac9b-4031-b6d3-44688e9bc63a</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>2jeUDtgO4Gv8oXOIDPWpMA==</ExceptionHash><Message>Subproceso anulado.</Message><StackTrace>   en DotNetNuke.Services.Scheduling.ProcessGroup.Run(ScheduleHistoryItem objScheduleHistoryItem)</StackTrace><InnerMessage /><InnerStackTrace /><Source>DotNetNuke</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="fcc5cb25-7b9a-456d-bc3e-557ad89c85f2" LogFileID="" LogTypeKey="SCHEDULER_EVENT_FAILURE" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>THREAD ID</PropertyName><PropertyValue>49</PropertyValue></LogProperty><LogProperty><PropertyName>TYPE</PropertyName><PropertyValue>DotNetNuke.Services.Search.SearchEngineScheduler, DOTNETNUKE</PropertyValue></LogProperty><LogProperty><PropertyName>EXCEPTION</PropertyName><PropertyValue>Subproceso anulado.</PropertyValue></LogProperty><LogProperty><PropertyName>RESCHEDULED FOR</PropertyName><PropertyValue>01/01/01 00:00:30</PropertyValue></LogProperty><LogProperty><PropertyName>SOURCE</PropertyName><PropertyValue>STARTED_FROM_TIMER</PropertyValue></LogProperty><LogProperty><PropertyName>ACTIVE THREADS</PropertyName><PropertyValue>-2</PropertyValue></LogProperty><LogProperty><PropertyName>FREE THREADS</PropertyName><PropertyValue>3</PropertyValue></LogProperty><LogProperty><PropertyName>READER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>WRITER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN PROGRESS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN QUEUE</PropertyName><PropertyValue>5</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="67005d25-0367-4c5c-a1c5-97261f153494" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="12/28/2015 12:11:45 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Sinapsis-03" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the Bin folder or files contained in it.</PropertyValue></LogProperty></LogProperties></log></logs>
=======
   en DotNetNuke.Services.Scheduling.ProcessGroup.Run(ScheduleHistoryItem objScheduleHistoryItem)</StackTrace><InnerMessage /><InnerStackTrace /><Source>DotNetNuke</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="f03cca3c-e850-4b87-b08a-f25e7037bccc" LogFileID="" LogTypeKey="SCHEDULER_EVENT_FAILURE" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>THREAD ID</PropertyName><PropertyValue>49</PropertyValue></LogProperty><LogProperty><PropertyName>TYPE</PropertyName><PropertyValue>DotNetNuke.Services.Search.SearchEngineScheduler, DOTNETNUKE</PropertyValue></LogProperty><LogProperty><PropertyName>EXCEPTION</PropertyName><PropertyValue>Subproceso anulado.</PropertyValue></LogProperty><LogProperty><PropertyName>RESCHEDULED FOR</PropertyName><PropertyValue>01/01/01 00:00:30</PropertyValue></LogProperty><LogProperty><PropertyName>SOURCE</PropertyName><PropertyValue>STARTED_FROM_TIMER</PropertyValue></LogProperty><LogProperty><PropertyName>ACTIVE THREADS</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>FREE THREADS</PropertyName><PropertyValue>2</PropertyValue></LogProperty><LogProperty><PropertyName>READER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>WRITER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN PROGRESS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN QUEUE</PropertyName><PropertyValue>5</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="59dd5faa-7bac-4513-9dc1-09ef220e4de4" LogFileID="" LogTypeKey="SCHEDULER_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>be8147e6-ac9b-4031-b6d3-44688e9bc63a</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>2jeUDtgO4Gv8oXOIDPWpMA==</ExceptionHash><Message>Subproceso anulado.</Message><StackTrace>   en DotNetNuke.Services.Scheduling.ProcessGroup.Run(ScheduleHistoryItem objScheduleHistoryItem)</StackTrace><InnerMessage /><InnerStackTrace /><Source>DotNetNuke</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="fcc5cb25-7b9a-456d-bc3e-557ad89c85f2" LogFileID="" LogTypeKey="SCHEDULER_EVENT_FAILURE" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="09/12/15 13:59:01" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID=""><LogProperties><LogProperty><PropertyName>THREAD ID</PropertyName><PropertyValue>49</PropertyValue></LogProperty><LogProperty><PropertyName>TYPE</PropertyName><PropertyValue>DotNetNuke.Services.Search.SearchEngineScheduler, DOTNETNUKE</PropertyValue></LogProperty><LogProperty><PropertyName>EXCEPTION</PropertyName><PropertyValue>Subproceso anulado.</PropertyValue></LogProperty><LogProperty><PropertyName>RESCHEDULED FOR</PropertyName><PropertyValue>01/01/01 00:00:30</PropertyValue></LogProperty><LogProperty><PropertyName>SOURCE</PropertyName><PropertyValue>STARTED_FROM_TIMER</PropertyValue></LogProperty><LogProperty><PropertyName>ACTIVE THREADS</PropertyName><PropertyValue>-2</PropertyValue></LogProperty><LogProperty><PropertyName>FREE THREADS</PropertyName><PropertyValue>3</PropertyValue></LogProperty><LogProperty><PropertyName>READER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>WRITER TIMEOUTS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN PROGRESS</PropertyName><PropertyValue>0</PropertyValue></LogProperty><LogProperty><PropertyName>IN QUEUE</PropertyName><PropertyValue>5</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="f0b76c4b-d234-4c90-92fa-176fe8b05ddb" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="0" LogPortalName="NEXSO" LogCreateDate="12/22/2015 4:41:00 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID="4"><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/Default.aspx</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>c7176cf4-98d9-4e9a-87c4-eb10d36c6a83</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>A++1f7m0EnksoPYj7r3g3Q==</ExceptionHash><Message>Unhandled Error: </Message><StackTrace /><InnerMessage>Object reference not set to an instance of an object.</InnerMessage><InnerStackTrace>   at DotNetNuke.Entities.Users.UserProfile.ClearIsDirty()
   at DotNetNuke.Security.Profile.DNNProfileProvider.GetUserProfile(UserInfo&amp; user)
   at DotNetNuke.Entities.Profile.ProfileController.GetUserProfile(UserInfo&amp; user)
   at DotNetNuke.Entities.Users.UserInfo.get_Profile()
   at DotNetNuke.Entities.Users.UserInfo.get_FirstName()
   at DotNetNuke.Security.Membership.AspNetMembershipProvider.UpdateUser(UserInfo user)
   at DotNetNuke.Entities.Users.UserController.UpdateUser(Int32 portalId, UserInfo user, Boolean loggedAction, Boolean clearCache)
   at DotNetNuke.HttpModules.Membership.MembershipModule.AuthenticateRequest(HttpContextBase context, Boolean allowUnknownExtensions)
   at DotNetNuke.HttpModules.Membership.MembershipModule.OnAuthenticateRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)</InnerStackTrace><Source /><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="ca262877-d853-4a43-bf4a-0313f8a89e1d" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="0" LogPortalName="NEXSO" LogCreateDate="12/27/2015 7:17:28 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="asuspc" LogConfigID="4"><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/Default.aspx</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>2f787c0b-84c7-4c95-be93-6b03aba07a04</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>667TTHD2oxCkbM3ECscyTg==</ExceptionHash><Message>Unhandled Error: </Message><StackTrace /><InnerMessage>Object reference not set to an instance of an object.</InnerMessage><InnerStackTrace>   at DotNetNuke.Entities.Users.UserProfile.ClearIsDirty()
   at DotNetNuke.Security.Profile.DNNProfileProvider.GetUserProfile(UserInfo&amp; user)
   at DotNetNuke.Entities.Profile.ProfileController.GetUserProfile(UserInfo&amp; user)
   at DotNetNuke.Entities.Users.UserInfo.get_Profile()
   at DotNetNuke.Entities.Users.UserInfo.get_FirstName()
   at DotNetNuke.Security.Membership.AspNetMembershipProvider.UpdateUser(UserInfo user)
   at DotNetNuke.Entities.Users.UserController.UpdateUser(Int32 portalId, UserInfo user, Boolean loggedAction, Boolean clearCache)
   at DotNetNuke.HttpModules.Membership.MembershipModule.AuthenticateRequest(HttpContextBase context, Boolean allowUnknownExtensions)
   at DotNetNuke.HttpModules.Membership.MembershipModule.OnAuthenticateRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)</InnerStackTrace><Source /><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="c4921cd7-575e-4d90-93fb-1c46533e3c8b" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="1/7/2016 4:58:53 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Sinapsis-03" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the Bin folder or files contained in it.</PropertyValue></LogProperty></LogProperties></log></logs>
>>>>>>> S﻿<log LogGUID="bdb7664f-0f9d-4ad9-8303-53b1d2aff2af" LogFileID="" LogTypeKey="PAGE_LOAD_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="fjimenez@sinapsis-innovation.com" LogPortalID="0" LogPortalName="NEXSO" LogCreateDate="3/10/2016 3:03:16 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="SINAPSIS-02" LogConfigID="6"><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/Default.aspx</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>db39d432-e33a-4638-87d8-00a438dd5b4a</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion>7.4.1</AssemblyVersion><PortalId>0</PortalId><UserId>48291</UserId><TabId>2844</TabId><RawUrl>/en-us/c/EconomiaNaranja/scoring</RawUrl><Referrer /><UserAgent>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</UserAgent><ExceptionHash>GuUqCD4C4lpufFRhiOWNqA==</ExceptionHash><Message>A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)</Message><StackTrace /><InnerMessage>A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)</InnerMessage><InnerStackTrace>   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByteArray(Byte[] buff, Int32 offset, Int32 len, Int32&amp; totalRead)
   at System.Data.SqlClient.TdsParser.TrySkipPlpValue(UInt64 cb, TdsParserStateObject stateObj, UInt64&amp; totalBytesSkipped)
   at System.Data.SqlClient.TdsParser.TrySkipValue(SqlMetaDataPriv md, Int32 columnOrdinal, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TrySkipRow(_SqlMetaDataSet columns, Int32 startCol, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TrySkipRow(_SqlMetaDataSet columns, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlDataReader.TryCloseInternal(Boolean closeReader)
   at System.Data.SqlClient.SqlDataReader.Close()
   at System.Data.Common.DbDataReader.Dispose(Boolean disposing)
   at System.Data.Common.DbDataReader.Dispose()
   at System.Data.Common.Internal.Materialization.Shaper`1.Finally()
   at System.Data.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.Dispose()
   at NZReportJudge.BindData() in d:\GITHUB\VS2013_PROJECT\NZPortalWeb\DesktopModules\Nexso\NZReportJudge\NZReportJudge.ascx.cs:line 122
   at NZReportJudge.Page_Load(Object sender, EventArgs e) in d:\GITHUB\VS2013_PROJECT\NZPortalWeb\DesktopModules\Nexso\NZReportJudge\NZReportJudge.ascx.cs:line 637
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)</InnerStackTrace><Source /><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method>System.Data.SqlClient.SqlConnection.OnError</Method></Exception></log>﻿<log LogGUID="bde5f484-f706-48b4-b91f-c6939fad1661" LogFileID="" LogTypeKey="PAGE_LOAD_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="Admin" LogPortalID="0" LogPortalName="NEXSO" LogCreateDate="4/8/2016 9:38:33 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="JAIROA" LogConfigID="6"><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/Default.aspx</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>29aec25f-9b68-4689-8bcd-0d939d4385b1</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>GJQk9zdwbPYdgnGODsNXuw==</ExceptionHash><Message>Failed to load viewstate.  The control tree into which viewstate is being loaded must match the control tree that was used to save viewstate during the previous request.  For example, when adding controls dynamically, the controls added during a post-back must match the type and position of the controls added during the initial request.</Message><StackTrace /><InnerMessage>Failed to load viewstate.  The control tree into which viewstate is being loaded must match the control tree that was used to save viewstate during the previous request.  For example, when adding controls dynamically, the controls added during a post-back must match the type and position of the controls added during the initial request.</InnerMessage><InnerStackTrace>   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)</InnerStackTrace><Source /><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log></logs>
